version: '3'

# Usage example: https://github.com/stilliard/docker-pure-ftpd/wiki/Docker-stack-with-Wordpress-&-FTP

services:
  ftpd_server:
    build: ./ftp_server
    container_name: ftp_server
    ports:
      - "21:21"
      - "30000-30099:30000-30099"
    volumes: # remember to replace /folder_on_disk/ with the path to where you want to store the files on the host machine
      - "./ftpuser:/home/ftpuser/"
      - "./ftpusers:/home/ftpusers/"
      - "./passwd:/etc/pure-ftpd/passwd"
# uncomment for ssl/tls, see https://github.com/stilliard/docker-pure-ftpd#tls
#      - "/folder_on_disk/ssl:/etc/ssl/private/"
    environment:
      PUBLICHOST: "localhost"
      FTP_PASSIVE_PORTS: "30000:30099"
      FTP_USER_NAME: ftpuser
      FTP_USER_PASS: tmfcffgocFtPGee0OoUe
      FTP_USER_HOME: /home/ftpuser
      FTP_MAX_CLIENTS: 50
      FTP_MAX_CONNECTIONS: 50
# also for ssl/tls:
#      ADDED_FLAGS: "--tls=2"
#    restart: always
